name: Build It
on: [push]

jobs:
  build:
    runs-on: debian-latest
    steps:
    - name: Build for Raspberry Pi 2/3/4 32 bit
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target armv7-unknown-linux-gnueabihf